---
count: 6
default:
  restart: 0
  wait: 0
editor:
  files:
    main:
      - lib/App/BitBucketCli.pm
      - lib/App/BitBucketCli/Core.pm
      - lib/App/BitBucketCli/Base.pm
    other:
      - lib/App/BitBucketCli/Project.pm
      - lib/App/BitBucketCli/Repository.pm
      - lib/App/BitBucketCli/Branch.pm
      - lib/App/BitBucketCli/PullRequest.pm
    link:
      - lib/App/BitBucketCli/Links.pm
      - lib/App/BitBucketCli/Link.pm
name: bitbucket-cli
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - bin
      - tests
  2:
    edit: main
  3:
    edit: other
  4:
    edit: link
  5:
    restart: 1
    edit: test
  6:
    restart: 1
    wait: 1
    edit:
      - bin
